[package]
name = "polyomino"
version = "0.1.0"
authors = ["Maros Grego"]
edition = "2018"
description = "A solver for polyomino kind puzzles"

[dependencies]
structopt = "0.2"

[lib]
name = "polyomino"
path = "src/lib.rs"

[[bin]]
name = "polyomino-solve"
path = "src/main.rs"
